---
resources:
  - name: git-repository
    type: git
    source:
      uri: https://github.com/devpro/cf-dotnet-samples.git
      branch: master
jobs:
  - name: build-webapp
    plan:
      - get: git-repository
        trigger: true
      - task: run-tests
        privileged: true
        config:
          platform: linux
          inputs:
            - name: git-repository
          image_resource:
            type: docker-image
            source:
              repository: microsoft/dotnet
              tag: 2.2-sdk
          run:
            path: sh
            args:
              - -exc
              - |
                ls -alrt
                cd ./git-repository/dotnetcore/2.2/webapp/
                dotnet build
